POST http://localhost:5000/api/room
Content-Type: application/json

{
    "name": "terest",
    "type": "audio",
    "description": "fdajsoi doasfdiao afdaoi adso fdsjai saodi foasijd isofaji aiojas dio jaiojfdas fdajsoi doasfdiao afdaoi adso fdsjai saodi foasijd isofaji aiojas dio jaiojfdas fdajsoi doasfdiao afdaoi adso fdsjai saodi foasijd isofaji aiojas dio jaiojfdas fdajsoi doasfdiao afdaoi adso fdsjai saodi foasijd isofaji aiojas dio jaiojfdas fdajsoi doasfdiao afdaoi adso fdsjai saodi foasijd isofaji aiojas dio jaiojfdas fdajsoi doasfdiao afdaoi adso fdsjai saodi foasijd isofaji aiojas dio jaiojfdas fdajsoi doasfdiao afdaoi adso fdsjai saodi foasijd isofaji aiojas dio jaiojfdas fdajsoi doasfdiao afdaoi adso fdsjai saodi foasijd isofaji aiojas dio jaiojfdas fdajsoi doasfdiao afdaoi adso fdsjai saodi foasijd isofaji aiojas dio jaiojfdas fdajsoi doasfdiao afdaoi adso fdsjai saodi foasijd isofaji aiojas dio jaiojfdas fdajsoi doasfdiao afdaoi adso fdsjai saodi foasijd isofaji aiojas dio jaiojfdas" 
}
